services:
  - type: web
    name: cmn-predracun
    runtime: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: cmn-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
